// ============================================================================
// WebRTC Type Definitions
// ============================================================================
// This file contains TypeScript interfaces for WebRTC signaling and
// mediasoup client-server communication. These types provide type safety
// across the WebRTC implementation.
// ============================================================================

// ============================================================================
// Transport Types
// ============================================================================

/**
 * WebRTC transport creation options
 */
export interface TransportOptions {
  socketId: string
  roomId: string
  forceTcp?: boolean
}

/**
 * WebRTC transport creation response
 * Contains ICE parameters, ICE candidates, and DTLS parameters needed for client-side transport creation
 */
export interface TransportCreatedData {
  id: string
  iceParameters: {
    usernameFragment: string
    password: string
    iceLite?: boolean
  }
  iceCandidates: Array<{
    foundation: string
    component: number
    protocol: 'udp' | 'tcp'
    address: string
    port: number
    priority: number
    type: 'host' | 'srflx' | 'prflx' | 'relay'
    tcpType?: string
  }>
  dtlsParameters: {
    role: 'auto' | 'client' | 'server'
    fingerprints: Array<{
      algorithm: string
      value: string
    }>
  }
}

// ============================================================================
// Producer Types
// ============================================================================

/**
 * Producer creation options
 */
export interface ProducerOptions {
  transportId: string
  kind: 'audio' | 'video'
  rtpParameters: any
  paused?: boolean
}

/**
 * Producer creation response
 */
export interface ProducerCreatedData {
  id: string
}

/**
 * New producer notification (sent to other participants)
 */
export interface NewProducerData {
  producerId: string
  userId: string
  kind: 'audio' | 'video'
}

// ============================================================================
// Consumer Types
// ============================================================================

/**
 * Consumer creation options
 */
export interface ConsumerOptions {
  producerId: string
  rtpCapabilities: any
}

/**
 * Consumer creation response
 */
export interface ConsumerCreatedData {
  id: string
  producerId: string
  kind: 'audio' | 'video'
  rtpParameters: any
}

// ============================================================================
// TURN/ICE Types
// ============================================================================

/**
 * ICE server configuration
 * Matches RTCIceServer interface from WebRTC API
 */
export interface IceServer {
  urls: string | string[]
  username?: string
  credential?: string
  credentialType?: 'password' | 'oauth'
}

/**
 * TURN credentials response
 * Generated by server using HMAC-SHA1 signature with TTL
 */
export interface TurnCredentials {
  username: string
  password: string
  ttl: number
}

/**
 * TURN credentials with ICE servers
 * Complete response for client WebRTC configuration
 */
export interface TurnCredentialsWithIceServers extends TurnCredentials {
  iceServers: RTCConfiguration['iceServers']
}

// ============================================================================
// Router Types
// ============================================================================

/**
 * Router RTP capabilities
 * Describes supported codecs and header extensions
 */
export interface RouterRtpCapabilitiesData {
  rtpCapabilities: {
    codecs: Array<{
      mimeType: string
      kind: 'audio' | 'video'
      clockRate: number
      channels?: number
      parameters?: Record<string, any>
    }>
    headerExtensions: Array<{
      kind: string
      uri: string
      preferredId: number
      preferredEncrypt: boolean
      direction?: string
    }>
  }
}

// ============================================================================
// Connection State Types
// ============================================================================

/**
 * WebRTC connection state
 * Tracks the state of client-side WebRTC connections
 */
export type ConnectionState =
  | 'new' // Connection created but not connected
  | 'connecting' // ICE gathering in progress
  | 'connected' // ICE connected, DTLS handshake complete
  | 'disconnected' // ICE disconnected (may reconnect)
  | 'failed' // Connection failed
  | 'closed' // Connection closed

/**
 * Transport connection state
 */
export type TransportState =
  | 'new'
  | 'connecting'
  | 'connected'
  | 'disconnected'
  | 'failed'
  | 'closed'

/**
 * Producer state
 */
export type ProducerState = 'pending' | 'playing' | 'paused' | 'failed' | 'closed'

/**
 * Consumer state
 */
export type ConsumerState = 'pending' | 'playing' | 'paused' | 'failed' | 'closed'

// ============================================================================
// Media Stream Types
// ============================================================================

/**
 * Media stream constraints for getUserMedia
 */
export interface MediaStreamConstraints {
  audio?: boolean | MediaTrackConstraints
  video?: boolean | MediaTrackConstraints
}

/**
 * Audio track constraints
 */
export interface AudioTrackConstraints {
  echoCancellation?: boolean
  noiseSuppression?: boolean
  autoGainControl?: boolean
  channelCount?: number
  sampleRate?: number
  sampleSize?: number
}

/**
 * Video track constraints
 */
export interface VideoTrackConstraints {
  width?: number | { min?: number; ideal?: number; max?: number }
  height?: number | { min?: number; ideal?: number; max?: number }
  frameRate?: number | { min?: number; ideal?: number; max?: number }
  aspectRatio?: number | { min?: number; ideal?: number; max?: number }
  facingMode?: 'user' | 'environment' | { ideal?: 'user' | 'environment' }
}

// ============================================================================
// Statistics Types
// ============================================================================

/**
 * WebRTC connection statistics
 * Used for monitoring connection quality
 */
export interface ConnectionStats {
  bitrate?: number // Current bitrate (kbps)
  packetLoss?: number // Packet loss percentage (0-100)
  rtt?: number // Round-trip time (ms)
  jitter?: number // Jitter (ms)
  bytesSent?: number // Total bytes sent
  bytesReceived?: number // Total bytes received
  packetsSent?: number // Total packets sent
  packetsReceived?: number // Total packets received
  packetsLost?: number // Total packets lost
}

/**
 * Connection quality level
 * Derived from connection statistics
 */
export type ConnectionQuality = 'excellent' | 'good' | 'fair' | 'poor'

/**
 * Connection quality info
 * Displayed to user as status indicator
 */
export interface ConnectionQualityInfo {
  quality: ConnectionQuality
  stats: ConnectionStats
  connectionType?: 'host' | 'srflx' | 'relay' // ICE candidate type
}
